DELETE http://localhost:3003/api/blogs/60e4c11bbb525a2f24879744
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZyZnJlZW1hbiIsImlkIjoiNjBkZjc1NTQzNTkxNjE0M2Q0ZTJlYjhiIiwiaWF0IjoxNjI1NjA0MzM4fQ.8RXzhXUIjwy5jG5Pi5gUwmIQlH60B8NrZpG_DKYX-3U