PUT http://localhost:3003/api/blogs/60e8c1bc89ffa44a649ccf6f
Content-Type: application/json

{
  "title": "Jest: a testing library",
  "author": "Ricky Montana",
  "url": "https://dev.com/Jest_a_testing_library",
  "likes": 100
}